version: "3.3"

services:

  hello_world:
    image: tutum/hello-world
    networks:
      - traefik-net
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-net
        - traefik.constraint-label=traefik-net
        - traefik.http.routers.hello-http.rule=Host(`hello.test.com`)
        - traefik.http.routers.hello-http.entrypoints=http
        - traefik.http.routers.hello-http.middlewares=https-redirect
        - traefik.http.routers.hello-https.rule=Host(`hello.test.com`)
        - traefik.http.routers.hello-https.entrypoints=https
        - traefik.http.routers.hello-https.tls=true
        - traefik.http.routers.hello-https.tls.certresolver=le
        - traefik.http.services.hello.loadbalancer.server.port=80
networks:
  traefik-net:
    external: true