version: "3.3"

services:
  whoami:
    image: "traefik/whoami"
    networks:
      - traefik-net
    deploy:
      labels:
        - "traefik.enable=true"
        - traefik.docker.network=traefik-net
        - traefik.constraint-label=traefik-net
        - "traefik.http.routers.whoami.rule=Host(`whoami.test.com`)"
        - "traefik.http.routers.whoami.entrypoints=http"
        - "traefik.http.routers.whoami.middlewares=https-redirect"

        - "traefik.http.routers.whoamis.rule=Host(`whoami.test.com`)"
        - "traefik.http.routers.whoamis.entrypoints=https"
        - "traefik.http.routers.whoamis.tls=true"
        - "traefik.http.routers.whoamis.tls.certresolver=le"

        - "traefik.http.services.whoami.loadbalancer.server.port=80"

networks:
  traefik-net:
    external: true